### ISSUE TITLE
Not working at all?

### ISSUE THREAD

**Issue by quomark** [compulim/react-scroll-to-bottom#106]
I have installed a whole new react app and also install react-scroll-to-bottom. When I apply your sample code nothing happen.
Here is the code and result:

![image](https://user-images.githubusercontent.com/89779542/140291685-a2179f5b-4f4c-443c-a644-19a61c9fb344.png)

**Comment by quomark** [comment]
The button is not shown. Scroll not happening..

**Comment by elliehachemjob** [comment]
https://codesandbox.io/s/react-scroll-to-bottom-test-forked-xy8sy 
this is a working test  

try to change your react-scroll-to-bottom version might work though
