### ISSUE TITLE
Conflicts with the drop-down loaded components being used

### ISSUE THREAD

**Issue by liwan11123123** [compulim/react-scroll-to-bottom#5]
![2](https://user-images.githubusercontent.com/43085718/48174188-e5a56000-e341-11e8-9b97-40eaf2d2b01d.gif)

Can you help me solve this conflict?
1. There seems to be a problem with the rolling bar monitor.
2. I have 20 data, I did not slide to the top, triggering refresh.

Please  Please  Please  。 Thanks you

**Comment by liwan11123123** [comment]
https://github.com/Broltes/react-touch-loader   Plug-in address used

**Comment by liwan11123123** [comment]
State context -> atTop().   How should this method be used?

**Comment by compulim** [comment]
You can track the issue at PR #8.

**Comment by compulim** [comment]
Should be fixed in 1.3.0.
