### ISSUE TITLE
Why doesn't % work when styling height ?

### ISSUE THREAD

**Issue by johannb75** [compulim/react-scroll-to-bottom#57]
Hey,
Thanks for the library.
I have an issue with styling of my component.
I'm trying to make my element responsive using `%` in `CSS`.
The problem is that when I use `%` it doesn't work but when I change to a static value (`px` or a number), it works.
My code (that doesn't work):
```js
const style = css({
	height: "100%", //if I change this to a static value (`px` or a number),  it works
});
<div className="mobile_chat_content">
	<ScrollToBottom mode="bottom" className={style}>
		<button onClick={scrollToBottom}>
			Click me to scroll to bottom
		</button>
		{messages.map((message, i) => (
		       <Message
			   key={message.id}
			   text={message.content}
		        />
		))}
	</ScrollToBottom>
</div>
```
I want my component to be responsive to the container, I can not change this to a static value
If anyone has suggestions to help me, it would be cool to let me know.
Thanks in advance.

**Comment by yo-png** [comment]
I'm having the same issue.
Maybe if you put a ref on your container and listen for the `on resize `event  you can generate a new class with the new height. 
Of course, I think there is a better solution to that because it would use a lot of memory if you generate a new class every time the component resizes.
What you could do, is to put every class and size in a multidimensional array:
```js
const classes = [
    ["the height", "the class name"],
    ["the height", "the class name"]
]
```
And after:
```js
const getIndexOfK = (arr, k) => {
  for (var i = 0; i < arr.length; i++) {
    var index = arr[i].indexOf(k);
    if (index > -1)  return [i, index];    
  }
}
containerRef.current.onresize = function(){
    const height = containerRef.current.offsetHeight
    const location = getIndexOfK(classes, height);
    let className;
    if(location === undefined){
       className = css({ height })
       classes.push([height, className])
    }else className = classes[location[0]][1]
    
    //update state variable containing class name

}
```
I seriously don't think it's the best solution but it works!
Anyone else ?

**Comment by johannb75** [comment]
It works but as you said, it's not the best solution.
Thanks!
Anyone else ?

**Comment by pranavmehta** [comment]
Yes, this is a major bummer for me as well. I need my height to be responsive to fit the entire screen height.

**Comment by johannb75** [comment]
Do you mean this: 
```js
const className = css({
height: "100%",
width: "100%",
overflowY: "auto"
})

const Content = () => (
     <ScrollToBottom className={className}>
          <Content />
      </ScrollToBottom>
)
```

Cause for me it isn't working.

**Comment by johannb75** [comment]
Actually i just figured out the porblem, it's because the container did not have `height: 100%`.
Thanks!
