### ISSUE TITLE
Add ref prop instead of hooks

### ISSUE THREAD

**Issue by johannb75** [compulim/react-scroll-to-bottom#59]
It would be much easier if instead of using hooks like `useScrollToBottom` just add a `ref` prop and add all the methods inside.
What I mean: 
```js
const App = () => {
   const scrollRef = useRef();

   const scroll = () => {
     scrollRef.current.scrollToBottom()
     //and all other hooks like useSticky
     if(scrollRef.current.isSticky()) console.log('is sticky')
   }
   return (
        <ScrollToBottom mode="bottom" ref={scrollRef}>
             <button onClick={scroll}>
                  Scroll
              </button>
              <Content />
        </ScrollToBottom>
   )
}
```

**Comment by yo-png** [comment]
Hope that @compulim will read that.

**Comment by compulim** [comment]
> Will finally do a release on my real world job next week. Hopefully get some down time at least on weekends. `react-scroll-to-bottom` is top thing on my hobby list. But instead of working on any features/bugs, I want to set up an automated end-to-end visual regression test, with experiences from my real world job. 😉

Why would it be easier when comparing to hooks?

```js
const App = () => {
   const scrollToBottom = useScrollToBottom();
   const [isSticky] = useSticky();

   const scroll = () => {
     scrollToBottom()
     //and all other hooks like useSticky
     if(isSticky) console.log('is sticky')
   };
   return (
        <ScrollToBottom mode="bottom" ref={scrollRef}>
             <button onClick={scroll}>
                  Scroll
              </button>
              <Content />
        </ScrollToBottom>
   )
}
```

One nice thing about hook, is that, when `sticky` is changed, your UI will get re-rendered automatically.

For example, I want to render something when `sticky` change. With hooks, I could:

```js
const StickyBadge = () => {
  const [sticky] = useSticky();

  return <div>{sticky ? 'Sticky' : 'Not sticky'}</div>;
};
```

But in your case, if `isSticky` change, your UI can't be re-rendered. Then, we need to expose another thing like, `scrollRef.current.addEventListener('stickychange', () => {}` and it will quickly make things complicated.

```js
const StickyBadge = () => {
  const [_, setRefresh] = useState();
  const forceRefresh = useCallback(() => setRefresh({}), [setRefresh]);
  
  useEffect(() => {
    scrollRef.current.addEventListener('stickychange', forceRefresh);

    return () => scrollRef.current.removeEventListener('stickychagne', forceRefresh);
  }, []);

  return <div>{scrollRef.current.isSticky() ? 'Sticky' : 'Not sticky'}</div>;
};
```

**Comment by johannb75** [comment]
What would be cool is change every method like `useScrollTo`, `useScrollToBottom`,  `useScrollToTop`... in a `ref` prop. And let all other hooks. It would reduce the code and take less memory since we won't have to create a variable for every method.

**Comment by compulim** [comment]
There are things that `ref` don't work out and `use` hooks can play out smoothly. The memory is a non-issue because it is very tiny compare to other stuff.

You can also use React Context to control the component and it will re-render when any of the props are updated. Here demonstrates how to use the [`FunctionContext`](https://github.com/compulim/react-scroll-to-bottom/blob/master/packages/component/src/ScrollToBottom/FunctionContext.js) and [`StateContext`](https://github.com/compulim/react-scroll-to-bottom/blob/master/packages/component/src/ScrollToBottom/StateContext.js).

```js
import { FunctionContext, StateContext } from 'react-scroll-to-bottom';

const App = () => {
   const { scrollToBottom } = useContext(FunctionContext);
   const { sticky } = useContext(StateContext);

   const scroll = () => {
     scrollToBottom()
     //and all other hooks like useSticky
     if(sticky) console.log('is sticky')
   };
   return (
        <ScrollToBottom mode="bottom">
             <button onClick={scroll}>
                  Scroll
              </button>
              <Content />
        </ScrollToBottom>
   )
}
```

**Comment by johannb75** [comment]
But how can i do in this case:
```js
const App = () => {
   const scrollToBottom = useScrollToBottom();
   <div>
     <div className="container">
        <ScrollToBottom>
           <Text>Hi</Text>
        </ScrollToBottom>
    </div>
    <div className="footer>
       <button className="scrollDown" onClick={scrollToBottom}>
           Scroll to bottom
        </button>
    </div>
  </div>
}
```

**Comment by compulim** [comment]
This is advacned. But you can do it by recomposing `<ScrollToBottom>` using the `<Composer>`.

This `<Composer>` is a headless component, i.e. no DOM element. It won't affect your layout. You can put it at the root of your page. But preferably, the common ancestor between the scrollable view and the button.

```js
import { AutoHideFollowButton, Composer, Panel } from 'react-scroll-to-bottom';

const App = () => {
  return (
    <Composer>
      <div className="container">
        <Panel>
          <Content />
          <AutoHideFollowButton />
        <Panel>
      </div>
      <div className="footer">
        <button onClick={scrollToBottom}>Scroll to bottom</button>
      </div>
    </Composer>
  );
};
```

**Comment by johannb75** [comment]
My point is that with `ref` it wouldn't be difficult:
```js
const scrollRef = useRef();
   <div>
     <div className="container">
        <ScrollToBottom ref={scrollRef}>
           <Text>Hi</Text>
        </ScrollToBottom>
    </div>
    <div className="footer>
       <button className="scrollDown" onClick={scrollRef.current.scrollToBottom()}>
           Scroll to bottom
        </button>
    </div>
  </div>
```

**Comment by compulim** [comment]
`ref` will send pointers everywhere. While it looks easy for now, it will be difficult for you to maintain later.

You can also send the React Context as a ref.

**Comment by compulim** [comment]
I hope you can use my component o run your project for a long time. When giving choices, I always choose "easy to maintain" over "easy to code". The technical debt built up isn't easy to tame.

If you follow my real world project, you will see how many things I added to make sure it is easily maintainable even the project has only 1-2 engineers to work on.

**Comment by johannb75** [comment]
Could you add in the documentation how to use `Composer`, `Panel`, etc ..

**Comment by compulim** [comment]
Sure. In the meanwhile, please copy my code first.

The current `README.md` also have some typos I should fix it sooner.

Thanks for understanding. I really hope your project shine for a long time. This is the reason I created this component.

**Comment by johannb75** [comment]
Thanks!

**Comment by johannb75** [comment]
When will you update the doc ??

**Comment by compulim** [comment]
Updated. For the separated DOM tree (a.k.a. recomposition), please refer to https://github.com/compulim/react-scroll-to-bottom/blob/master/samples/recomposition.html.

**Comment by johannb75** [comment]
Could you add a documentation instead of an example it would much easier to understand the role of each component
