### ISSUE TITLE
Debug always on

### ISSUE THREAD

**Issue by albireox** [compulim/react-scroll-to-bottom#75]
It seems that debs is always on, regardless of whether I pass `debug={false}` or not. Am I missing something?

**Comment by gnattu** [comment]
If your `NODE_ENV ` is set to debug it will also print debug info in the console.

**Comment by ankit1738** [comment]
Changed the `NODE_ENV`, still prining the render statements in console

**Comment by clarchiu** [comment]
also have this issue

**Comment by AkileshAro** [comment]
Have the same issue

**Comment by liamzety** [comment]
same here

**Comment by compulim** [comment]
Will look at this one.

**Comment by compulim** [comment]
I have fixed this in latest development build: setting `debug={false}` will be honored and overrode what is provided over `NODE_ENV`.

The development build that got this fix is `4.1.1-master.2780945`.

Once I fix other issues, will release a build with production version number.

**Comment by justinbhopper** [comment]
@compulim Thank you for adding this fix.  Are there known bugs in 4.1.1 preview that is holding up adding a production version release?

**Comment by parjosuparjo** [comment]
when is the production version released to fix this issue?
