### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by parveezahamed** [compulim/react-scroll-to-bottom#79]
I am getting process is not defined.

![react-scroll-to-bottom](https://user-images.githubusercontent.com/11803717/109477380-f68fb780-7a9d-11eb-8eb0-650186afa6e5.PNG)

**Comment by justinbhopper** [comment]
Getting this too.  I'm trying to run a react app in Electron, and so process is not a global variable (unless I make the app insecure by enabling node integration).

**Comment by compulim** [comment]
This should be fixed, we removed `process.env` usage from `debug.js`.

Please open a new issue if you are seeing it again.
